name: spacerplacer_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python<3.13       # need this due to ete3 cgi package issue
  - numpy>=1.21.4
  - pandas>=1.3.4
  - seaborn>=0.11.2
  - matplotlib>=3.4.3
  - scipy>=1.7.1
  - ete3>=3.1.2
  - palettable>=3.3.0
  - graphviz>=0.20.1
  - sympy>=1.11.1
  - mafft>=7.490
  - biopython>=1.79
  - python-graphviz>=0.17
  - dill>=0.3.5.1
